# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devspecs < Formula
  desc "DevSpecs CLI — index and reference your specs, plans, and ADRs"
  homepage "https://github.com/devspecs-com/devspecs-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devspecs-com/devspecs-cli/releases/download/v0.1.0/devspecs_0.1.0_darwin_x86_64.tar.gz"
      sha256 "2e154ad0e26a8c51b79772e7e7bd8b73620e43ed40b900ac6909a2fe63506abb"

      define_method(:install) do
        bin.install "ds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devspecs-com/devspecs-cli/releases/download/v0.1.0/devspecs_0.1.0_darwin_arm64.tar.gz"
      sha256 "95295f78f638acc0c10dfbdeb30171a3c48199b6cae40409c6b7fc8c5a0fdf4a"

      define_method(:install) do
        bin.install "ds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devspecs-com/devspecs-cli/releases/download/v0.1.0/devspecs_0.1.0_linux_x86_64.tar.gz"
      sha256 "a16a1a01faeffd38ff56c8ce09c82866e279c5cbb9baeea5401ac91c9f8b9706"
      define_method(:install) do
        bin.install "ds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devspecs-com/devspecs-cli/releases/download/v0.1.0/devspecs_0.1.0_linux_arm64.tar.gz"
      sha256 "9615147b84fb9f441c19ae1768ede53a0ec3ab0d930319bcca8937ede688c564"
      define_method(:install) do
        bin.install "ds"
      end
    end
  end

  test do
    system "#{bin}/ds", "--version"
  end
end
